port: 32001
vault:
  token : "root"
  vault_host : localhost:8200
redis :
  redis_password : <redis_password>
  redis_host : localhost:6379
  max_idle_in_sec : 600
  idle_timeout_in_sec : 1
postgres :
  postgres_config : <postgres_config>
nsq :
  producer_host : localhost:4150
  consumer_host : localhost:4161
farm_handler :
  timeout_in_sec : 5
pond_handler :
  timeout_in_sec : 5
stat_handler :
  timeout_in_sec : 5
  backup_time_in_minute : 5
tracking_event :
  topic : aqua_farm_tracking_event
  channel : tracking_event
  max_in_flight: 30
  num_of_consumer: 2
  timeout_in_sec: 3