// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\gilsp\go\src\user-manager\internal\service\user\user.go

// Package mock_user is a generated GoMock package.
package mock_user

import (
	user "gilsaputro/user-manager/internal/service/user"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserServiceMethod is a mock of UserServiceMethod interface.
type MockUserServiceMethod struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMethodMockRecorder
}

// MockUserServiceMethodMockRecorder is the mock recorder for MockUserServiceMethod.
type MockUserServiceMethodMockRecorder struct {
	mock *MockUserServiceMethod
}

// NewMockUserServiceMethod creates a new mock instance.
func NewMockUserServiceMethod(ctrl *gomock.Controller) *MockUserServiceMethod {
	mock := &MockUserServiceMethod{ctrl: ctrl}
	mock.recorder = &MockUserServiceMethodMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceMethod) EXPECT() *MockUserServiceMethodMockRecorder {
	return m.recorder
}

// AddUser mocks base method.
func (m *MockUserServiceMethod) AddUser(arg0 user.AddUserServiceRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockUserServiceMethodMockRecorder) AddUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockUserServiceMethod)(nil).AddUser), arg0)
}

// DeleteUser mocks base method.
func (m *MockUserServiceMethod) DeleteUser(arg0 user.DeleteUserServiceRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserServiceMethodMockRecorder) DeleteUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserServiceMethod)(nil).DeleteUser), arg0)
}

// GetAllUserWithPagging mocks base method.
func (m *MockUserServiceMethod) GetAllUserWithPagging(arg0 user.GetAllUserWithPaggingServiceRequest) (user.GetAllUserWithPaggingServiceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUserWithPagging", arg0)
	ret0, _ := ret[0].(user.GetAllUserWithPaggingServiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUserWithPagging indicates an expected call of GetAllUserWithPagging.
func (mr *MockUserServiceMethodMockRecorder) GetAllUserWithPagging(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUserWithPagging", reflect.TypeOf((*MockUserServiceMethod)(nil).GetAllUserWithPagging), arg0)
}

// GetUserByID mocks base method.
func (m *MockUserServiceMethod) GetUserByID(arg0 user.GetByIDServiceRequest) (user.UserServiceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", arg0)
	ret0, _ := ret[0].(user.UserServiceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserServiceMethodMockRecorder) GetUserByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserServiceMethod)(nil).GetUserByID), arg0)
}

// LoginUser mocks base method.
func (m *MockUserServiceMethod) LoginUser(arg0 user.LoginUserServiceRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUser", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockUserServiceMethodMockRecorder) LoginUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockUserServiceMethod)(nil).LoginUser), arg0)
}

// RegisterUser mocks base method.
func (m *MockUserServiceMethod) RegisterUser(arg0 user.RegisterUserServiceRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockUserServiceMethodMockRecorder) RegisterUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockUserServiceMethod)(nil).RegisterUser), arg0)
}

// UpdateUser mocks base method.
func (m *MockUserServiceMethod) UpdateUser(arg0 user.UpdateUserServiceRequest) (user.UserServiceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0)
	ret0, _ := ret[0].(user.UserServiceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserServiceMethodMockRecorder) UpdateUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserServiceMethod)(nil).UpdateUser), arg0)
}
